/*
 * Copyright(c) 2016 Phạm Minh Hoàng
 * Framework:	MyClasses
 * Description:	This script is generated by MyUGUIConfigIDEditorWindow
 */

namespace MyClasses.UI
{
    public enum EUnitySceneID
    {
        StartupUnityScene,
        MainMenuUnityScene,
        GameplayUnityScene,
    }

    public enum ESceneID
    {
        LoginScene,
        MainMenuScene,
        GameplayScene,
    }

    public enum EPopupID
    {
        Dialog0ButtonPopup,
        Dialog1ButtonPopup,
        Dialog2ButtonsPopup,
    }
}